// --[ Action Constants ]------------------------------------------------------

export const SIGNING_CHANGE_FORM = 'SIGNING_CHANGE_FORM'
export const SIGNING_SET_AUTH = 'SIGNING_SET_AUTH'
export const SIGNING_SENDING_REQUEST = 'SIGNING_SENDING_REQUEST'
export const SIGNING_LOGIN_REQUEST = 'SIGNING_LOGIN_REQUEST'
export const SIGNING_REGISTER_REQUEST = 'SIGNING_REGISTER_REQUEST'
export const SIGNING_LOGOUT = 'SIGNING_LOGOUT'
export const SIGNING_REQUEST_ERROR = 'SIGNING_REQUEST_ERROR'
export const SIGNING_CLEAR_ERROR = 'SIGNING_CLEAR_ERROR'

export const ADD_CELL_CHANGE_FORM = 'ADD_CELL_CHANGE_FORM'
export const ADD_CELL_SENDING_REQUEST = 'ADD_CELL_SENDING_REQUEST'
export const ADD_CELL_REQUEST = 'ADD_CELL_LOGIN_REQUEST'
export const ADD_CELL_REQUEST_ERROR = 'ADD_CELL_REQUEST_ERROR'
export const ADD_CELL_CLEAR_ERROR = 'ADD_CELL_CLEAR_ERROR'
